version: "3"

services:
  # api:
  #   build:
  #     context: ./api/docker
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8000:80
  #   volumes:
  #     - ./api:/var/www

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
