version: "3"

services:
  api:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./api:/var/www
    networks:
      - mynetwork

  mercure:
    image: dunglas/mercure
    environment:
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
      MERCURE_SUBSCRIBER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    networks:
      - mynetwork
    ports:
      - 8002:80
    volumes:
      - mercure_data:/data
      - mercure_config:/config

  db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mercure_data:
  mercure_config:
  my-db:
