version: "3"

services:
  api:
    build:
      context: ./api/docker
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./api:/var/www
    networks:
      - mynetwork
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./docker/db/data:/var/lib/mysql:rw
    networks:
      - mynetwork

networks:
  mynetwork:
